### ISSUE TITLE
Milestone2 Report

### ISSUE THREAD

**Issue by tkyilmaz** [bounswe/bounswe2017group4#145]
Milestone2 report will be added to the Wiki page and milestone presentation also will be added to the master branch. Due to:09.12.2017 15:00

**Comment by amerty95** [comment]
I added MS2 presantation to the master branch

**Comment by tkyilmaz** [comment]
Report is also added to the master. Commit:51b7d0b8613ad9366b3959fef6dedfc14383ebe3
