### ISSUE TITLE
Final methods for API

### ISSUE THREAD

**Issue by tkyilmaz** [bounswe/bounswe2017group4#160]
Final methods will be implemented

**Comment by emreun** [comment]
e59a3fa93594cd6331b0f271e483cedc73a25a7c
3d04f4bf886b18a7a5a76737f97e5b7adb5fd185
4367572d1b4042e01381aa50385052c37046a407

**Comment by tkyilmaz** [comment]
editResponse and deleteResponse are added.

**Comment by tkyilmaz** [comment]
Related commits:
70d842553510a4fbf2bba567c7becb0ce1ad90e3
644c0deb2886f5a784d58b8b292fb891f9f128ad
