### ISSUE TITLE
Admin user requirements

### ISSUE THREAD

**Issue by tkyilmaz** [bounswe/bounswe2017group4#23]

**Comment by tkyilmaz** [comment]
I think we need a subsection about admin user requirements. Here are some thoughts.
-Admin user shall have a specific password.
-Admin shall be able to add, change or delete filters.
-Chatbot shall be able to show to admin general user's info.
-Chatbot shall be able to show to admin comments and ratings of a book.
     - It shall be able to show the ratings by each user.(where general user shall be able to see only average rating).
-Admin user shall be able to remove inappropiate comments.
-Admin user shall be able to block users who continuously do inappropiate comments.
-Admin user shall be able to shut down the system if the system is under attack.

If you think that these are not requirement or need some corrections and changes please leave a comment. If there are someting missing, add these requirements also in your comment.

**Comment by berkerol** [comment]
I added these admin user requirements to projects requirements.
