### ISSUE TITLE
Mock-Up for user comment and rate system

### ISSUE THREAD

**Issue by berkerol** [bounswe/bounswe2017group4#24]
Create a mock-up for user comment and rate system
Due: 28/02/2017

**Comment by caglarhizli** [comment]
[admin_comment_mobile_draft.pdf](https://github.com/bounswe/bounswe2017group4/files/802145/admin_comment_mobile_draft.pdf)

**Comment by caglarhizli** [comment]
[user_comment_mobile_draft.pdf](https://github.com/bounswe/bounswe2017group4/files/802146/user_comment_mobile_draft.pdf)

**Comment by berkerol** [comment]
[Untitled project.pdf](https://github.com/bounswe/bounswe2017group4/files/802164/Untitled.project.pdf)

**Comment by berkerol** [comment]
done
