### ISSUE TITLE
Fixing the issues in feedback

### ISSUE THREAD

**Issue by berkerol** [bounswe/bounswe2017group4#25]
We have many issues in feedback on Piazza regarding both requirements and communication plan.
We should fix them as soon as possible.
Everyone should comment here about what they are going to fix.

**Comment by tkyilmaz** [comment]
I can update the communication plan page.
Regarding the requirements I can fix: 1.2.1  & 1.2.3 and I will do some thinking about missing requirements as well.

**Comment by berkerol** [comment]
I fixed the issues in 1.1.3. & 1.1.4. and some of the issues about 1.2 (__it__ removed, 1.2.2., 1.2.3., 1.2.4. are fixed).

**Comment by gurbuzbeyza** [comment]
I will put 1.1.1. and 1.1.2. under system requirements and add a purpose to 1.2.4.
Edit: I put 1.1.1. and 1.1.2. under system requirements. I also changed the subject of 1.1.3, 1.1.4, and 1.1.5 to user.

**Comment by caglarhizli** [comment]
I can check non-functional requirements tonight.
@koseus, I saw your comments on Piazza regarding 2.1, 2.3.1, 2.4 and 2.9. Should we keep them same as the current requirement doc?

**Comment by berkerol** [comment]
I fixed some small issues and fixed indentation of the whole text.

**Comment by gurbuzbeyza** [comment]
I changed the requirements under 1.1.1.1. to 'shall be able to'
