### ISSUE TITLE
Fixing the issues in Mockup reviews

### ISSUE THREAD

**Issue by berkerol** [bounswe/bounswe2017group4#28]
We have some issues in mock-up reviews on Piazza regarding all mock-ups.
We should fix them as soon as possible.
Everyone should comment here about what they are going to fix.

**Comment by koseus** [comment]
I can take the following

- Telegram UI 2
- Conversation graph edit 1 and 2

**Comment by berkerol** [comment]
I have added flag comment/user option for admin user and report comment/user option for generic user in the user comments and ratings mock-up.
