### ISSUE TITLE
Create use case scenarios

### ISSUE THREAD

**Issue by tkyilmaz** [bounswe/bounswe2017group4#32]
Create scenarios for general user's interactions:
-See other user's comment
-See rating of the books
-Report comment/user

**Comment by koseus** [comment]
Create scenarios for admin user's interactions:
- Login
- Reset password
- Sign up

**Comment by berkerol** [comment]
I have created the following use case scenarios for admin users' interactions
* View all general users' profiles
* View all general users' ratings for a book
* View all general users' comments for a book
* View reports of comments and general users
* Flag comments and general users
* Delete comments
* Suspend general users

I also contributed the following use case scenarios
* Flag comment(s)/user(s)
