### ISSUE TITLE
Questions for Customer Meeting

### ISSUE THREAD

**Issue by berkerol** [bounswe/bounswe2017group4#45]
We are going to have a second customer meeting soon. We have some questions about the recently created content.
It is better to discuss and collect our questions here and then ask our customer what they need.

**Comment by tkyilmaz** [comment]
What interface do we use when user comments or rates a book? Telegram or another interface that we create?

**Comment by koseus** [comment]
What kind of account suspension do you want? One that is removed manually by the admin, one that has duration defined and removed automatically when the duration expires, or both?

**Comment by berkerol** [comment]
We had our customer meeting.
