### ISSUE TITLE
Create Project Plan

### ISSUE THREAD

**Issue by tkyilmaz** [bounswe/bounswe2017group4#47]
I've started a little bit with Project Plan and I added the subparts Documentation(including requirements, communication plan etc.) Mockups and Diagrams. If you write here which part do you take, there will be no confusion,

**Comment by amerty95** [comment]
I will add project name, implementation and testing parts, I will also add milestone names in necessary places in project plan.

**Comment by caglarhizli** [comment]
I'll group **Design** part with the following subparts:

- **Design** involves _Use Case Diagram_, _Use Cases_ and _Use Case Scenarios_, _Class Diagram_, _Sequence Diagrams_ and _Data Model Design_ subparts.

**Comment by caglarhizli** [comment]
Also added a milestone detail page for _MS1: Requirements and Mockups_
