### ISSUE TITLE
Questions for Customer Meeting

### ISSUE THREAD

**Issue by tkyilmaz** [bounswe/bounswe2017group4#87]
We can collect our questions for the customer meeting under this issue. 
Due to: 28.09.2017 12.00

**Comment by amerty95** [comment]
-Do users need to open an account to use chatbot, if so do we have to collect and store their information(like their phone number from telegram account) for operations like book suggestions.
-When a user comments on a book by using chatbot, do we link the usernames with the comments or will comments be shown anonymously.
-Do we have to develop an application for mobile devices seperately from Telegram development.(Last semester our asistant wanted to add a seperate mobile development but later we weren't assigned a task about it)
-Can comments and ratings  be seen only withing chatbot by texting or do we develop a seperate system for showing the comments and ratings of books.

**Comment by sabeniacar** [comment]
-Should the user's knowledge/level of the subject be taken into account when s/he is querying for a book, If yes, how? Should the user specify his level of the subject on his profile(if exists) or when he is querying?

**Comment by guneykan** [comment]
-Since the user will possibly have different level of knowledge for different subjects, we may need to store the level of the user for different subjects or not store any information but ask the user for each new query. This issue does not seem to be clear yet.

**Comment by ozerbiber** [comment]
-We need a clarification about changing the default sentences of the chatbot by admin users.

**Comment by tkyilmaz** [comment]
In the project plan, is it enough that only estimated time for back-end, front-end implementation is shown?
If not how do we show the steps for our progress? For example in particular time period we will implement code part for a certain requirement. Is it necessary for project plan?
